
// 企業の属性の列挙
const CompanyTag = {
  // --- 業界・事業モデル ---
  AI: "AI",
  BtoB: "BtoB",
  BtoBtoC: "BtoBtoC",
  BtoC: "BtoC",
  D2C: "D2C",
  DXSupport: "DX支援",
  EC: "EC",
  EdTech: "EdTech",
  HRTech: "HRテック",
  IoT: "IoT",
  IT: "IT",
  SaaS: "SaaS",
  WebService: "Webサービス",
  Anime: "アニメ",
  Apparel: "アパレル",
  Infrastructure: "インフラ",
  Entertainment: "エンタメ",
  Energy: "エネルギー",
  Cloud: "クラウド",
  Game: "ゲーム",
  Consulting: "コンサルティング",
  Subscription: "サブスクリプション",
  Security: "セキュリティ",
  Design: "デザイン",
  Fintech: "フィンテック",
  Platform: "プラットフォーム",
  Healthcare: "ヘルスケア",
  Hotel: "ホテル",
  Marketing: "マーケティング",
  MassMedia: "マスコミ",
  Manufacturer: "メーカー",
  RealEstate: "不動産",
  Insurance: "保険",
  Medical: "医療",
  Space: "宇宙",
  Tourism: "観光",
  Education: "教育",
  Finance: "金融",
  Advertising: "広告",
  AssetManagement: "資産運用",
  InHouseServiceDevelopment: "自社サービス開発",
  ContractDevelopment: "受託開発",
  Publishing: "出版",
  TradingCompany: "商社",
  InformationAndCommunication: "情報通信",
  Food: "食品",
  HumanResources: "人材",
  ProductionCompany: "制作会社",
  ProfessionalServices: "専門サービス",
  Strategy: "戦略",
  Agriculture: "農業",
  Semiconductor: "半導体",
  Logistics: "物流",
  Legal: "法律",
  VentureCapital: "ベンチャーキャピタル",
  Retail: "小売",

  // --- 企業規模・ステージ ---
  NicheTop: "ニッチトップ",
  Venture: "ベンチャー",
  MegaVenture: "メガベンチャー",
  SmallEliteTeam: "少数精鋭",
  ListedCompany: "上場企業",
  LargeCorporation: "大企業",
  SME: "中小企業", // Small and Medium-sized Enterprises
  JapaneseCompany: "日系",
  UnlistedCompany: "非上場",
  ForeignCompany: "外資系",
  RapidlyGrowing: "急成長中",
  Subsidiary: "子会社",
  EstablishedCompany: "老舗企業",
  EstablishedWithin5Years: "設立5年以内",
  StableManagement: "安定経営",
  DebtFreeManagement: "無借金経営",
  Startup: "スタートアップ",

  // --- カルチャー・働き方 ---
  Has1on1System: "1on1制度あり",
  AtHome: "アットホーム",
  InsideSales: "インサイドセールス",
  Global: "グローバル",
  Diversity: "ダイバーシティ",
  TopDown: "トップダウン",
  FlatOrganization: "フラットな組織",
  FlexTime: "フレックス",
  FullFlexTime: "フルフレックス",
  FullRemote: "フルリモート",
  BottomUp: "ボトムアップ",
  RemoteWork: "リモートワーク",
  OverseasExpansion: "海外展開",
  PlanningPosition: "企画職",
  CultureAcceptingFailure: "失敗を許容する文化",
  Meritocracy: "実力主義",
  ManyYoungEmployees: "若手が多い",
  ManyCompanyEvents: "社内イベント多い",
  ManyFemaleManagers: "女性管理職が多い",
  CustomerService: "接客",
  PursueSpecialization: "専門性を追求",
  CasualDressCode: "服装自由",
  ShortenedWorkingHoursAvailable: "時短勤務可",
  ChallengingEnvironment: "挑戦できる環境",
  RegionalRevitalization: "地方創生",
  SenioritySystem: "年功序列",
  SideJobsOK: "副業OK",
  FastDecisionMaking: "意思決定が速い",
  CanUseEnglishSkills: "英語力が活かせる",
  TeamworkOriented: "チームワーク重視",

  // --- 制度・福利厚生 ---
  CleanOffice: "オフィスが綺麗",
  StockOptionsAvailable: "ストックオプションあり",
  FreeDrinks: "ドリンク無料",
  MentorshipSystem: "メンター制度",
  LunchSubsidy: "ランチ補助",
  RentSubsidy: "家賃補助",
  Over120AnnualHolidays: "年間休日120日以上",
  TechBookPurchaseSupport: "技術書購入補助",
  ExtensiveTrainingSystem: "研修制度が充実",
  CertificationSupport: "資格取得支援",
  FullTransportationAllowance: "交通費全額支給",
  MaternityPaternityLeaveRecord: "産休・育休実績あり",
  RetirementPlan: "退職金制度",
  GenerousBenefits: "福利厚生が充実",

  // --- ミッション・バリュー ---
  ContributesToSDGs: "SDGsに貢献",
  EcoFriendly: "エコ",
  PurposeDriven: "パーパス経営",
  TechnologyFocused: "技術力重視",
  FocusOnRandD: "研究開発に注力",
  CustomerFirst: "顧客第一主義",
  SocialContribution: "社会貢献",
  ManyPatents: "特許多数",
  HasADream: "夢がある",
} as const;
export type CompanyTag = typeof CompanyTag[keyof typeof CompanyTag];